apiVersion: apps/v1 

kind: Deployment 

metadata: 

  name: web-deploy

spec: 

  replicas: 3 

  selector: 

    matchLabels: 

      name: web-pod

  template: 

    metadata: 

      labels: 

        name: web-pod

    spec: 

      containers: 

      - name: web-container 

        image: tasneemsherif/docker_imageweb
        ports:
         - containerPort: 80